<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BasePluginModule extends Doctrine_Record
{

    public function setTableDefinition()
    {
        $this->setTableName('plugin_modules');
        $this->hasColumn('id', 'integer', 4, array('unsigned' => 1, 'primary' => true, 'notnull' => true, 'autoincrement' => true));
        $this->hasColumn('plugin_id', 'integer', 4, array('unsigned' => 1, 'primary' => false, 'default' => '', 'notnull' => true, 'autoincrement' => false));
        $this->hasColumn('module_type', 'enum', 7, array('fixed' => false, 'values' =>  array( 0 => 'Action',  1 => 'Trigger', ), 'primary' => false, 'default' => '', 'notnull' => true, 'autoincrement' => false));
        $this->hasColumn('display_name', 'string', 255, array('fixed' => false, 'primary' => false, 'default' => '', 'notnull' => true, 'autoincrement' => false));
        $this->hasColumn('status', 'enum', 8, array('fixed' => false, 'values' =>  array( 0 => 'Enabled',  1 => 'Disabled', ), 'primary' => false, 'default' => 'Enabled', 'notnull' => true, 'autoincrement' => false));
        $this->hasColumn('classname', 'string', 255, array('fixed' => false, 'primary' => false, 'default' => '', 'notnull' => true, 'autoincrement' => false));
        $this->hasColumn('path', 'string', null, array('fixed' => false, 'primary' => false, 'default' => '', 'notnull' => true, 'autoincrement' => false));
        $this->hasColumn('module_config', 'string', null, array('fixed' => false, 'primary' => false, 'notnull' => false, 'autoincrement' => false));
        $this->hasColumn('ordering', 'integer', 4, array('unsigned' => 0, 'primary' => false, 'default' => '0', 'notnull' => true, 'autoincrement' => false));
        $this->hasColumn('can_disable', 'integer', 1, array('unsigned' => 1, 'primary' => false, 'default' => '0', 'notnull' => true, 'autoincrement' => false));
        $this->hasColumn('namespace', 'string', 255, array('fixed' => false, 'primary' => false, 'default' => '', 'notnull' => true, 'autoincrement' => false));
        $this->hasColumn('dependencies', 'string', null, array('fixed' => false, 'primary' => false, 'default' => '', 'notnull' => true, 'autoincrement' => false));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Plugin', array('local' => 'plugin_id', 'foreign' => 'id'));
    }

}