<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Base_Document extends Doctrine_Record
{

  public function setTableDefinition()
  {
    $this->setTableName('documents');
    $this->hasColumn('id', 'integer', 4, array('unsigned' => 0, 'primary' => true, 'default' => '0', 'notnull' => true, 'autoincrement' => false));
    $this->hasColumn('creator_id', 'integer', 4, array('unsigned' => 0, 'primary' => false, 'notnull' => false, 'autoincrement' => false));
    $this->hasColumn('modified', 'timestamp', null, array('primary' => false, 'default' => '0000-00-00 00:00:00', 'notnull' => true, 'autoincrement' => false));
    $this->hasColumn('folder_id', 'integer', 4, array('unsigned' => 0, 'primary' => false, 'notnull' => false, 'autoincrement' => false));
    $this->hasColumn('is_checked_out', 'integer', 1, array('unsigned' => 0, 'primary' => false, 'default' => '0', 'notnull' => true, 'autoincrement' => false));
    $this->hasColumn('parent_folder_ids', 'string', null, array('fixed' => false, 'primary' => false, 'notnull' => false, 'autoincrement' => false));
    $this->hasColumn('full_path', 'string', null, array('fixed' => false, 'primary' => false, 'notnull' => false, 'autoincrement' => false));
    $this->hasColumn('checked_out_user_id', 'integer', 4, array('unsigned' => 0, 'primary' => false, 'notnull' => false, 'autoincrement' => false));
    $this->hasColumn('status_id', 'integer', 4, array('unsigned' => 0, 'primary' => false, 'notnull' => false, 'autoincrement' => false));
    $this->hasColumn('created', 'timestamp', null, array('primary' => false, 'default' => '0000-00-00 00:00:00', 'notnull' => true, 'autoincrement' => false));
    $this->hasColumn('permission_object_id', 'integer', 4, array('unsigned' => 0, 'primary' => false, 'notnull' => false, 'autoincrement' => false));
    $this->hasColumn('permission_lookup_id', 'integer', 4, array('unsigned' => 0, 'primary' => false, 'notnull' => false, 'autoincrement' => false));
    $this->hasColumn('metadata_version', 'integer', 4, array('unsigned' => 0, 'primary' => false, 'default' => '0', 'notnull' => true, 'autoincrement' => false));
    $this->hasColumn('modified_user_id', 'integer', 4, array('unsigned' => 0, 'primary' => false, 'notnull' => false, 'autoincrement' => false));
    $this->hasColumn('metadata_version_id', 'integer', 4, array('unsigned' => 0, 'primary' => false, 'notnull' => false, 'autoincrement' => false));
    $this->hasColumn('owner_id', 'integer', 4, array('unsigned' => 0, 'primary' => false, 'notnull' => false, 'autoincrement' => false));
    $this->hasColumn('immutable', 'integer', 1, array('unsigned' => 0, 'primary' => false, 'default' => '0', 'notnull' => true, 'autoincrement' => false));
    $this->hasColumn('restore_folder_id', 'integer', 4, array('unsigned' => 0, 'primary' => false, 'notnull' => false, 'autoincrement' => false));
    $this->hasColumn('restore_folder_path', 'string', null, array('fixed' => false, 'primary' => false, 'notnull' => false, 'autoincrement' => false));
    $this->hasColumn('checkedout', 'timestamp', null, array('primary' => false, 'notnull' => false, 'autoincrement' => false));
    $this->hasColumn('oem_no', 'string', 255, array('fixed' => false, 'primary' => false, 'notnull' => false, 'autoincrement' => false));
  }

  public function setUp()
  {
    parent::setUp();
    $this->hasOne('Base_Folder as Folder', array('local' => 'folder_id', 'foreign' => 'id'));
    $this->hasOne('Base_DocumentMetadatumVersion as MetadataVersion', array('local' => 'metadata_version_id', 'foreign' => 'id'));

//    $this->hasMany('Base_DocumentContentVersion as ContentVersion', array('local' => 'id', 'foreign' => 'document_id'));

//    $this->hasOne('Base_User as User', array('local' => 'creator_id', 'foreign' => 'id'));
  }

}