<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Base_DocumentContentVersion extends Doctrine_Record
{

  public function setTableDefinition()
  {
    $this->setTableName('document_content_version');
    $this->hasColumn('id', 'integer', 4, array('unsigned' => 0, 'primary' => true, 'default' => '0', 'notnull' => true, 'autoincrement' => false));
    $this->hasColumn('document_id', 'integer', 4, array('unsigned' => 0, 'primary' => false, 'default' => '0', 'notnull' => true, 'autoincrement' => false));
    $this->hasColumn('filename', 'string', null, array('fixed' => false, 'primary' => false, 'default' => '', 'notnull' => true, 'autoincrement' => false));
    $this->hasColumn('size', 'integer', 8, array('unsigned' => 0, 'primary' => false, 'default' => '0', 'notnull' => true, 'autoincrement' => false));
    $this->hasColumn('mime_id', 'integer', 4, array('unsigned' => 0, 'primary' => false, 'default' => '9', 'notnull' => false, 'autoincrement' => false));
    $this->hasColumn('major_version', 'integer', 4, array('unsigned' => 0, 'primary' => false, 'default' => '0', 'notnull' => true, 'autoincrement' => false));
    $this->hasColumn('minor_version', 'integer', 4, array('unsigned' => 0, 'primary' => false, 'default' => '0', 'notnull' => true, 'autoincrement' => false));
    $this->hasColumn('storage_path', 'string', 250, array('fixed' => false, 'primary' => false, 'notnull' => false, 'autoincrement' => false));
    $this->hasColumn('md5hash', 'string', 32, array('fixed' => true, 'primary' => false, 'notnull' => false, 'autoincrement' => false));
  }

  public function setUp()
  {
    parent::setUp();
    $this->hasOne('Base_Document as Document', array('local' => 'document_id', 'foreign' => 'id'));

//    $this->hasOne('Base_DocumentMetadatumVersion as MetadataVersion', array('local' => 'id', 'foreign' => 'content_version_id'));

  }

}